
CREATE DATABASE EuroQuest;

USE EuroQuest;

CREATE TABLE IF NOT EXISTS `user` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL,
	`role` ENUM('admin', 'customer') NOT NULL DEFAULT 'customer',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `country` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`country_name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `city` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`city_name` VARCHAR(255) NOT NULL,
	`country_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `hotels` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`city_id` INTEGER NOT NULL,
	`amount_of_rooms` INTEGER NOT NULL,
	`description` TEXT(65535) NOT NULL,
	`beach_distance` INTEGER NOT NULL COMMENT 'avstånd till strand',
	`pool` TINYINT NOT NULL,
	`breakfast` TINYINT NOT NULL,
	`center_distance` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `rooms` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`number` INTEGER NOT NULL,
	`hotels_id` INTEGER NOT NULL,
	`capacity` INTEGER NOT NULL,
	`price` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `activity` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`duration` INTEGER NOT NULL,
	`price` INTEGER NOT NULL,
	`address` VARCHAR(255) NOT NULL,
	`city_id` INTEGER NOT NULL,
	`capacity` INTEGER NOT NULL,
	`description` TEXT(65535) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `package` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`hotel_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `package_activity` (
	`package_id` INTEGER NOT NULL,
	`activity_id` INTEGER NOT NULL,
	PRIMARY KEY(`package_id`, `activity_id`)
);


CREATE TABLE IF NOT EXISTS `bookings` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`package_id` INTEGER NOT NULL,
	`user_id` INTEGER NOT NULL,
	`check_in` DATE NOT NULL,
	`check_out` DATE NOT NULL,
	`guests` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `room_booking` (
	`booking_id` INTEGER NOT NULL,
	`room_id` INTEGER NOT NULL,
	PRIMARY KEY(`booking_id`, `room_id`)
);


ALTER TABLE `city`
ADD FOREIGN KEY(`country_id`) REFERENCES `country`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `hotels`
ADD FOREIGN KEY(`city_id`) REFERENCES `city`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `rooms`
ADD FOREIGN KEY(`hotels_id`) REFERENCES `hotels`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `activity`
ADD FOREIGN KEY(`city_id`) REFERENCES `city`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `package`
ADD FOREIGN KEY(`hotel_id`) REFERENCES `hotels`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `package_activity`
ADD FOREIGN KEY(`package_id`) REFERENCES `package`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `package_activity`
ADD FOREIGN KEY(`activity_id`) REFERENCES `activity`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bookings`
ADD FOREIGN KEY(`package_id`) REFERENCES `package`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bookings`
ADD FOREIGN KEY(`user_id`) REFERENCES `user`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `room_booking`
ADD FOREIGN KEY(`booking_id`) REFERENCES `bookings`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `room_booking`
ADD FOREIGN KEY(`room_id`) REFERENCES `rooms`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
